// playground/react/src/components/Button/index.tsx
import {
  ContextSchema,
  SealFunctionComponent,
  useSealAction,
} from '@seal-container/react-render'

type ButtonAction = {
  click: () => void
}

type ButtonSchema = ContextSchema<ButtonAction>

interface ButtonProps {
  content?: string
}

const Button: SealFunctionComponent<ButtonProps, ButtonSchema> = (props) => {
  const action = useSealAction<ButtonAction>()

  return (
    <button
      onClick={() => {
        action.exec('click')
      }}
    >
      {props.content}
    </button>
  )
}

export default Button

// playground/vue/src/components/Button.tsx
// import { ContextSchema, SealComponent } from '@seal-container/core-runtime'
import {
  ContextSchema,
  SealComponent,
  useSealAction,
} from '@seal-container/vue-render'
import { defineComponent } from 'vue'
// import { useSealAction } from '../../src'

type ButtonAction = {
  click: () => void
}

type ButtonSchema = ContextSchema<ButtonAction>

const Button = defineComponent({
  setup() {
    const action = useSealAction<ButtonAction>()
    return () => {
      return <button onClick={() => action.exec('click')}></button>
    }
  },
})

export default Button as SealComponent<typeof Button, ButtonSchema>
