// packages/react/__test__/components/Count.tsx
import { ContextSchema, SealComponent } from '@seal-container/core-runtime'
import {
  Children,
  FunctionComponent,
  PropsWithChildren,
  ReactElement,
  isValidElement,
  useMemo,
  useState,
} from 'react'
import { useSealAction } from '../../src'

type CountAction = {
  increment: (step?: number) => void
  decrement: (step?: number) => void
}

export type CountSchema = ContextSchema<CountAction>

interface CountProps {}

const Count: FunctionComponent<PropsWithChildren<CountProps>> = (props) => {
  const [count, setCount] = useState(0)

  const slotsNodes = useMemo(() => {
    const slotsNodes: Record<string, ReactElement[]> = {}
    const children = Children.toArray(props.children)
    for (const child of children) {
      if (isValidElement(child)) {
        const slotName = child.props.value.slot ?? 'default'
        slotsNodes[slotName] ??= []
        slotsNodes[slotName].push(child)
      }
    }
    return slotsNodes
  }, [])

  const action = useSealAction<CountAction>((action) => {
    action.on('decrement', (step = 1) => {
      setCount((count) => count - step)
    })

    action.on('increment', (step = 1) => {
      setCount((count) => count + step)
    })
  })

  return (
    <div>
      {slotsNodes.decrement ?? (
        <button onClick={() => action.exec('decrement')}>-</button>
      )}
      <span>{count}</span>
      {slotsNodes.increment ?? (
        <button onClick={() => action.exec('increment')}>+</button>
      )}
    </div>
  )
}

export default Count as SealComponent<typeof Count, CountSchema>

// playground/vue/src/components/Count.tsx
import {
  ContextSchema,
  SealComponent,
  useSealAction,
} from '@seal-container/vue-render'
import { VNode, defineComponent, ref } from 'vue'

type CountAction = {
  increment: (step?: number) => void
  decrement: (step?: number) => void
}

type CountSchema = ContextSchema<CountAction>

const Count = defineComponent({
  setup(_, { slots }) {
    const count = ref(0)

    const action = useSealAction<CountAction>((action) => {
      action.on('decrement', (step = 1) => {
        count.value -= step
      })

      action.on('increment', (step = 1) => {
        count.value += step
      })
    })

    return () => {
      const children = slots.default?.() ?? []
      const slotDom: Record<string, VNode[]> = {}

      for (const child of children) {
        const slotName = child.props?.value.slot ?? 'default'
        slotDom[slotName] ??= []
        slotDom[slotName].push(child)
      }

      return (
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          {slotDom.decrement ?? (
            <button onClick={() => action.exec('decrement')}>-</button>
          )}
          <span>{count.value}</span>
          {slotDom.increment ?? (
            <button onClick={() => action.exec('increment')}>+</button>
          )}
        </div>
      )
    }
  },
})

export default Count as SealComponent<typeof Count, CountSchema>
