// playground/vue/src/components/Button.tsx
// import { ContextSchema, SealComponent } from '@seal-container/core-runtime'
import {
  ContextSchema,
  SealComponent,
  useSealAction,
} from '@seal-container/vue-render'
import { defineComponent } from 'vue'
// import { useSealAction } from '../../src'

type ButtonAction = {
  click: () => void
}

type ButtonSchema = ContextSchema<ButtonAction>

const Button = defineComponent({
  setup() {
    const action = useSealAction<ButtonAction>()
    return () => {
      return <button onClick={() => action.exec('click')}></button>
    }
  },
})

export default Button as SealComponent<typeof Button, ButtonSchema>

// packages/react/__test__/components/Button.tsx
import { ContextSchema, SealComponent } from '@seal-container/core-runtime'
import { FunctionComponent } from 'react'
import { useSealAction } from '../../src'

type ButtonACtion = {
  click: () => void
}

export type ButtonSchema = ContextSchema<ButtonACtion>

interface ButtonProps {
  label: string
}

const Button: FunctionComponent<ButtonProps> = (props) => {
  const action = useSealAction<ButtonACtion>()

  return <button onClick={() => action.exec('click')}>{props.label}</button>
}

export default Button as SealComponent<typeof Button, ButtonSchema>
